aws/aws-xray-daemon

daemon/conn/conn.go
Enable shared config when creating session.
https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-local.html seems to indicate that daemon will honor environment variables. This change will allow it to honor the `AWS_PROFILE` variable from a machine with `~/.aws/credentials` and `~/.aws/config` .  Another fix would be just to update documentation to mention the `AWS_SDK_LOAD_CONFIG` in the daemon documentation. 
=> Create session using NewSessionWithOptions

glide.lock, glide.yaml
#31
This will be eclipsed by #32 which migrates to go.mod. I am opening this to enable faster rollout if needed. 
=> Bumping up aws-sdk-go to enable IAM Roles for Service Account in Kubernetes

makefile
We try our best to clean up the build folder but do not fail if any delete fails, so we don't block the live builds.
=> Do not fail when cleaning build folder

daemon/conn/conn.go, daemon/conn/conn_test.go
40
Added ECS metadata as a fallback option for getting the region when EC2 metadata is unavailable.
=> Support for fetching region from ECS metadata

README.md
Remove dependency management instruction for Glide since we have moved to go.mod now
=> Remove Glide instruction

pkg/telemetry/telemetry.go
On my EKS workers I [restricted the access to Amazon EC2 instance metadata service](https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html) and thus the end point http://169.254.169.254 isn't reachable.
A possible workaround is to start xray-daemon with `--local-mode`, but since xray need it for just 3 fields (region, hostname and instance-id), I think it's OK to set those via environment variables as well.
=> Allow to set hostname and instance-id when EC2 metadata is blocked

pkg/processor/batchprocessor.go
Logging dropped segments at 'warn' level leaks customer data.
=> Don't leak customer traces at default log level

pkg/processor/batchprocessor.go, pkg/processor/batchprocessor_test.go
https://github.com/aws/aws-xray-daemon/issues/63
If part of segments break the x-ray rules like invalid ID, at present the log is:
```
2020-08-11T22:59:59-07:00 [Info] Successfully sent batch of 2 segments (0.064 seconds)
```
This fix improves log detail, if there are Unprocessed segments returned, print:
```
2020-08-11T23:00:15-07:00 [Info] Sent batch of 2 segments but had 1 Unprocessed segments (0.080 seconds)
```
=> not print `successfully` if there are Unprocessed segments

pkg/processor/batchprocessor.go, pkg/ringbuffer/ringbuffer.go
https://github.com/aws/aws-xray-daemon/issues/62
remove N^2 redundant logging
=> reduce debug logging

pkg/processor/batchprocessor.go, pkg/processor/batchprocessor_test.go
https://github.com/aws/aws-xray-daemon/issues/63
Only log unprocessed segments by comparing the IDs.
Here because batches is a string slice, filter the unprocessed segments by matching string 'id' will get complexity O(m*n). 
To reduce the complexity we create a map for batches.
=> debug logging print only unprocessed segments detail

.dockerignore, .github/workflows/continuous-build.yml, .travis.yml, Dockerfile, cmd/tracing/tracing.go, cmd/tracing/tracing_windows.go
This adds a GitHub actions continuous build that builds on the three main OS's and a Docker image. In a follow up PR, we can also set up creds and have it pushing to Docker Hub. In a similar follow up PR we can remove the Travis build too.
Currently, the published Docker Hub image has cgo enabled. cgo is mostly needed when using other c libraries, and otherwise may provide better DNS resolutions on not-so-well supported platforms, but on the major OSs it's basically not needed. OTel collector also doesn't use it to make building easier. So instead, we get a statically linked binary suitable for the scratch docker base image. This will be a good default for our next release.
I also removed a deployment section from travis, it hasn't been used yet and presumably we don't want to push docker …
=> GitHub actions continuous build

README.md, cmd/tracing/daemon.go, pkg/cfg.yaml, pkg/cfg/cfg.go, pkg/cfg/cfg_test.go, pkg/conn/conn.go, pkg/conn/conn_test.go
Reverts aws/aws-xray-daemon#76
AWS SDK supports Credential profile by environment variable [`AWS_PROFILE`](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_environment.html), I have verified in my environment. No need this PR.
=> Revert "Support credential profiles"

makefile
Adding symbol CGO_ENABLED=0, to build xray daemon Linux statically linked binary. 
Before
```
dev-dsk-wangzl-2c-e7c31da9 % make build-linux
Build for Linux amd64
GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o /local/home/wangzl/workspace/aws-xray-daemon/build/xray/xray ./cmd/tracing/daemon.go ./cmd/tracing/tracing.go
(20-11-03 19:27:05) <0> [~/workspace/aws-xray-daemon]
dev-dsk-wangzl-2c-e7c31da9 % ls -l build/xray/xray
-rwxr-xr-x 1 wangzl amazon 9531392 Nov  3 19:27 build/xray/xray
(20-11-03 19:27:09) <0> [~/workspace/aws-xray-daemon]
dev-dsk-wangzl-2c-e7c31da9 % ldd build/xray/xray
linux-vdso.so.1 =>  (0x00007fff0d0ed000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2c10cef000)
libc.so.6 => /lib64/libc.so.6 (0x00007f2c1095b000) …
```
=> build statically linked binary on linux

README.md
https://github.com/aws/aws-xray-daemon/issues/74
AWS go  SDK does support `source_profile` but has to enable it by setting environment `AWS_SDK_LOAD_CONFIG=1`.
Improve user guide to be easily find the document how to set credential configuration in go sdk.
=> add html anchor tag for go sdk credentials configuration

.dockerignore, .github/workflows/continuous-build.yml, Dockerfile, Tool/src/build-in-docker.sh
Updates Dockerfile to copy binaries that have already been built if they exist to avoid having multiple ground-truth binaries.
=> Use prebuilt binaries for docker image too.

Tool/src/packaging/debian/build_deb_linux.sh, makefile
- Updating the packaging script to package the linux arm64 type daemon in aws-xray-daemon-linux-amd64-.deb and aws-xray-daemon-linux-arm64-.deb binaries.
=> Debian packaging for amd64 and arm64

.github/workflows/continuous-build.yml, Tool/src/packaging/linux/build_rpm_linux.sh, makefile
In the previous builds of the CI, the rpm was breaking due to `VERSION` not being set in the environment. Added that. Also modifying the script to build the arm64 type rpm for the daemon.
=> Packaging daemon into amd64 and arm64 type rpm

.github/workflows/continuous-build.yml, .github/workflows/release-build-publish.yml, Tool/src/packaging/build-package-legacy.sh, Tool/src/packaging/debian/build_deb_linux.sh, Tool/src/packaging/linux/build_zip_linux.sh, Tool/src/packaging/osx/build_zip_osx.sh, Tool/src/packaging/windows/build_zip_win.sh, makefile
Since the current workflow builds and packages daemon artifacts with names which are different than what are currently officially vended, I'm adding a script to generate the older artifacts in addition to the new ones. We plan to maintain both the names until the next major version release to keep the backward compatibility intact.
PR which introduced new artifact names: https://github.com/aws/aws-xray-daemon/pull/84
=> adding job to build old name artifacts

.github/workflows/release-build-publish.yml, pkg/logger/log_config.go
1. Set `prod` log level to `warn` level because currently `prod` is set at `info` level which is still more verbose than `warn`
Reference Git issue: https://github.com/aws/aws-xray-daemon/issues/95
=> Info log fix

Tool/src/packaging/debian/xray.service, Tool/src/packaging/linux/xray.service
For systemd, the `simple` service type we were using would always return success to the system manager when running the X-Ray daemon process even if executing the daemon binary wasn't successful. The `exec` type only returns success once the binary is executed successfully, which provides a more expected and explicit failure mode if the binary is not executed successfully.
Source: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Options
=> Change linux service type

.github/workflows/continuous-build.yml, .github/workflows/release-build-publish.yml, Tool/src/packaging/osx/build_zip_osx.sh, go.mod, go.sum, makefile
Updates build to use Go 1.16 and adds mac-arm64
=> Add mac arm64 build using go 1.16

Tool/src/packaging/build-package-legacy.sh
*Issue #, if available:
As per [documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon.html) there are 9 binaries with different OS/Arch and we were missing copying/creating linux arm64 daemon zip file
=> Bugfix - Adding linux arm64 zip file in legacy packaging

.github/workflows/continuous-monitoring.yml, .github/workflows/release-build-publish.yml
This change introduces continuous monitoring of Dockerhub and public ECR. Based on failure/success it publishes metrics to cloud watch. The purpose of this workflow is to publish metrics so that we can continuously monitoring availability of docker hub and ECR.  Also, we are publishing metrics on pulled daemon image is start-able or not so that we can be well aware about image corruption/security issues with the latest release.
The workflow is scheduled to run every 6 hours.
=> Continuous monitoring Dockerhub and public ECR

.github/workflows/continuous-monitoring.yml
monitor-ecr job of [continuous monitoring workflow](https://github.com/aws/aws-xray-daemon/actions/workflows/continuous-monitoring.yml) fails intermittently with `toomanyrequests: Rate exceeded` so added login to aws account step to avoid such throttling exceptions
=> Fix: Intermittent pull failure issue

Tool/src/packaging/debian/build_deb_linux.sh
**Issue**
When trying to install the `aws-xray-daemon-linux-amd64-338157a78c973c312308e7f1ad9b83b233554bc3.deb` from the latest CI build, I got the following error:
```
dpkg: error processing archive distribution_wo_sign/aws-xray-daemon-linux-amd64-338157a78c973c312308e7f1ad9b83b233554bc3.deb (--install):
parsing file '/var/lib/dpkg/tmp.ci/control' near line 3 package 'xray':
field name '-1' cannot start with hyphen
```
Looking into the debian package, I found the `control` file to like this:
```
Package: xray
Architecture: amd64
Version: 338157a78c973c312308e7f1ad9b83b233554bc3
-1
Section: admin
Depends: libc6
Priority: optional
Copyright: Apache License, Version 2.0
Suggests: aws-xray-doc
Maintainer: Amazon.com, Inc. <aws-xray@amazon.com>
Description: Amazon X-Ray is a platform makes it …
```
=> Removing -1 suffix from version causing bug

pkg/processor/batchprocessor.go, pkg/processor/batchprocessor_test.go, pkg/processor/processor.go
https://github.com/aws/aws-xray-daemon/issues/120
Daemon need to handle the exceptional case that sending invalid format to x-ray, x-ray returns an unprocessed segment with `nil` id. 
=> check unprocessed segment id is nill

pkg/logger/log_config.go
In 3.3.0 the default log output level is `Warn`, that suppresses daemon startup log
revert #97 
=> revert Info log fix #97

.github/workflows/continuous-build.yml, .github/workflows/release-build-publish.yml, .github/workflows/release-publish-Dockerhub.yml, pkg/logger/log_config.go
*Issue #, if available:* #128, #119
- Adding a separate GH workflow to build the daemon image from amazonlinux as base
- Updating the existing workflow to publish `major.x` image tag to public ECR
=> Workflow - Publish DockerHub image built on amazonlinux

Dockerfile, Dockerfile.amazonlinux
#135
Adds the binding options for Daemon to listen on all network interfaces, and exposes port 2000 to UDP and TCP traffic, on both Dockerfiles used for ECR & Dockerhub publishing. This will fix a regression with the 3.3.x releases.
=> Fixed Dockerfiles regression

pkg/profiler/profiler.go, pkg/proxy/server.go, pkg/socketconn/udp/udp.go, pkg/tracesegment/tracesegment.go
I saw that some of the calls such as closing a file, closing a response body return a error, but they are not checked and not even logged. I am adding support to handle that case
=> Add logs for ignored errors

Dockerfile, Dockerfile.amazonlinux
A recent issue brought to our notice that the [v3.3.2](https://hub.docker.com/layers/amazon/aws-xray-daemon/3.3.2/images/sha256-5af3311579a9ea50f23677fc6cea0eab7539c866c62905c89862cf902f24c638?context=explore) (3.x and latest as well) DockerHub image diverged from [v3.2.0](https://hub.docker.com/layers/amazon/aws-xray-daemon/3.2.0/images/sha256-b220818a0c4bd0b71224356dfb14eb0b173ae11a00e45aa86e6be9d843f19193?context=explore) and had it's `entrypoint` changed from `/usr/bin/xray` to `/xray`. This caused problem when a user specifically tried to start daemon using the previous entrypoint.
-This PR adds a symlink for entrypoint to `/usr/bin/xray` 
=> Changing copy and entrypoint location for xray

pkg/proxy/server.go
#144 
Changes the log-level and wording of the error message when the proxy server stops listening. I also audited other log messages added in #138 but the rest appear to be legitimate errors that should still be logged as such.
=> change server listen error log to info

.github/workflows/continuous-build.yml, .github/workflows/release-build-publish.yml, .github/workflows/release-publish-Dockerhub.yml
Currently we are comfortable with taking whatever 1.16.x version is resolved to when publishing the daemon images, however we'd like to have at least Go v1.16.6 for its bug & security fixes.
=> Enforce go1.16.6 as minimum version in actions

.github/workflows/continuous-build.yml, .github/workflows/release-build-publish.yml
Using IAM role instead of IAM user for ECR publishing
Need to add new github secrete `AWS_ASSUME_ROLE_ARN_RELEASE`, and merge it at the end of MCM.
=> use OIDC auth for ECR publishing

.github/workflows/release-build-publish.yml
The "Create Release" step in the release workflow [fails](https://github.com/aws/aws-xray-daemon/runs/4599663089?check_suite_focus=true) with `Error: Resource not accessible by integration`. This is because the workflow's permissions for the repository content (includes creating release on the repo) is set to `read` which overwrites the default repo setting. 
Setting the `contents` permission to `write` to enable this workflow to create a draft release. I was able to test this change on my personal repo here: https://github.com/srprash/Workflow_Test/actions/runs/1609080628
=> Allow release workflow write access to create GH releases

.github/workflows/release-build-publish.yml, Dockerfile, Dockerfile.amazonlinux, go.mod, go.sum
Internally tracked
Bumping GO to version 1.18.
Bumping golang.org/x/text to v0.3.7 
Bumping golang.org/x/net to v0.0.0-20220809184613-07c6da5e1ced
Bumping golang.org/x/sys to v0.0.0-20220808155132-1c4a2a72c664
*Testing*
Ran 'make test'.
Ran the code in Docker. Validated that the container was running.
=> Fixing CVE issues by bumping GO and Text versions.

CHANGELOG.md, pkg/conn/xray_client.go
*Issue #, if available:* N/A
*Description of changes:* This PR reformats the structure of the user-agent string and captures relevant information (agent version, AWS execution environment if any, and OS data) in a uniform format that can be easily parsed. 
Current user-agent: 
```
aws-sdk-go/1.44.62 (go1.19; linux; amd64) exec-env/AWS_ECS_FARGATE xray/3.3.5 (AWS_ECS_FARGATE)
```
New user-agent:
```
aws-sdk-go/1.44.62 (go1.19.5; linux; amd64) xray-agent/xray-daemon/3.3.5 exec-env/UNKNOWN OS/linux-amd64
```
=> User-agent redesign - add additional information to user-agent

Dockerfile.amazonlinux
None
Hi!
The Dockerfile placed at "Dockerfile.amazonlinux" contains the best practice violation [DL3006](https://github.com/hadolint/hadolint/wiki/DL3006) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3006 occurs when the image tag for the base image is missing.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, we use a heuristic approach that selects the most probable version tag for the given base image. In detail, it selects the most recent image tag which corresponds to the same image digest that currently corresponds to the "latest" tag, used by default …
=> Fix for Dockerfile smell DL3006

pkg/conn/conn.go
During ALB maintainance, there could be cases where the TCP connection from Daemon to X-Ray ALB is not properly closed, the Daemon client will not know the TCP connection is no longer working, and will be kept using it for sending new HTTP2 requests as HTTP2 multplexes all the requests in a single TCP connection, this would results in repeated request timeouts and evetually losing data.
In this change 2 timeouts has been added:
* ReadIdleTimeout time.Duration
ReadIdleTimeout is the timeout after which a health check using ping frame will be carried out if no frame is received on the connection. Note that a ping response will is considered a received frame, so if there is no other traffic on the connection, the health check will be …
=> Add http2 timouts to close bad TCP connection

CHANGELOG.md
This reverts commit 56f6ee2e4fdacce34cbb9d692918f54dcfa2f936.
We will update DockerHub image without upgrading Daemon Version. 
=> Revert "Release commit v3.3.14 (#224)"

.github/workflows/continuous-build.yml, .github/workflows/release-build-publish.yml, Dockerfile, Dockerfile.amazonlinux, Tool/src/packaging/linux/build_rpm_linux.sh, Tool/src/packaging/linux/xray.spec
Addressing CVEs:
* 2024-34156
* 2024-34155
* 2024-34158
These CVEs affect Go versions before go1.22.7, from go1.23.0-0 before go1.23.1
=> upgrade golang to 1.23.6

.github/workflows/continuous-build.yml
Use actions/download-artifact@v4.
v3 is Deprecated - https://github.com/aws/aws-xray-daemon/actions/runs/13291457159
=> Use actions/download-artifact@v4

.github/workflows/release-build-publish.yml
The release build was broken because GitHub no longer supports actions/cache@v2.
This fix upgrades it to v4 in the release build workflow YAML file.
=> [Bld Break Fix] Upgrade actions/cache to v4 in release build

testing/terraform/amis.tf, testing/terraform/testcases/linux_deb.tfvars
Integration test job for Linux Debian system is failing in master branch due to dropped support for Ubuntu 18 image. Update image to 22.04 to pass test
=> Upgrade Ubuntu image for integration test

pkg/conn/xray_client.go
Fixes a logging bug where the daemon's debug output displays %!s(*string=<nil>) instead of properly handling the endpoint value.
During the AWS SDK v1 → v2 migration, the endpoint field changed from a string to a *string (pointer). The logging code wasn't updated to handle this type change, causing Go's formatter to display the malformed output when the endpoint is nil.
```
Using Endpoint: %!s(*string=<nil>)
```
SDK v1: `x.Endpoint (string)` SDK v2: `cfg.BaseEndpoint (*string)`
=> incorrect endpoint logging format in debug output

pkg/conn/conn.go, pkg/conn/conn_test.go, pkg/telemetry/telemetry.go
https://github.com/aws/aws-xray-daemon/issues/255
1. Use the default config to call IMDS in the telemetry.
Before the fix:
```
export HTTP_PROXY=http://api.example.com
export HTTPS_PROXY=https://api.example.com
export NO_PROXY="169.254.169.254,localhost,127.0.0.1"
./xray -o -n us-east-1 --log-level=debug --local-mode=false
2025-09-14T06:31:52Z [Debug] Get hostname metadata failed: operation error ec2imds: GetMetadata, request send failed, Get "http://169.254.169.254/latest/meta-data/hostname": proxyconnect tcp: dial tcp: lookup api.example.com on 172.31.0.2:53: no such host
2025-09-14T06:31:52Z [Error] Get instance id metadata failed: operation error ec2imds: GetMetadata, request send failed, Get …
```
=> Fix IMDS queries under proxies
