aws/aws-xray-daemon

Tool/src/packaging/debian/xray.service
Tool/src/packaging/linux/xray.service

This eliminates the need for a new shell during process execution and allows for end user environment variable overrides.  This also ensures that the necessary directories are in place when the process starts.

SystemD Service file updates

---

.travis.yml

Add Go 1.11 to Travis

---

Tool/src/packaging/debian/xray.service
Tool/src/packaging/linux/xray.service

*Issue #, if available:* #27 #28
set ConfigurationDirectoryMode to 0755 instead of 0700

xray.service: explicitly set ConfigurationDirectoryMode to 0755

---

README.md

Added daemon build instruction for arm64 architecture in README.

arm64 build instruction

---

README.md

The current instructions are unclear.

Adding more details to instructions for building for ARM

---

.github/workflows/continuous-build.yml

*Description of changes:* Docker creds configured as secrets so enables login and push.

Push alpha tag to Docker Hub on push.

---

README.md
cmd/tracing/daemon.go
pkg/cfg.yaml
pkg/cfg/cfg.go
pkg/cfg/cfg_test.go
pkg/conn/conn.go
pkg/conn/conn_test.go

*Issue #, if available: 74*
Added a new option (-s, --profile) to specify a credential profile

Support credential profiles

---

README.md

Modified README to add authentication instructions

Added authentication instruction to public ECR

---

pkg/processor/batchprocessor.go

https://github.com/aws/aws-xray-daemon/issues/104
Extract traceId from segment string by Regex

log traceId for unprocessed segments

---

.github/workflows/continuous-monitoring.yml

monitoring workflow will publish metric on every hour for better alarming

Change cron job time to 1 hr

---

CHANGELOG.md

Release commit v3.3.0

---

.github/workflows/release-build-publish.yml

Added dockerhub `latest` and `3.x` tags to publish as part of the release workflow 

Added dockerhub latest and 3.x tags

---

.github/workflows/release-build-publish.yml

Fix changelog link

---

CHANGELOG.md

Release commit v3.3.1

---

.github/workflows/continuous-build.yml
.github/workflows/continuous-monitoring.yml
Tool/src/integration/invalid_input.py

https://github.com/aws/aws-xray-daemon/issues/120
Verify invalid input in CI workflow

verify invalid input in CI

---

CHANGELOG.md

Adding release dates and the docker image change note

---

.github/workflows/continuous-build.yml

Fix CI account permission and typo issue

fix CI typo, verify invalid input

---

CHANGELOG.md

release 3.3.2
1. Fix log missing
2. Rollback Dockerhub image base to AmazonLinux

Release commit v3.3.2

---

.github/workflows/continuous-build.yml
.github/workflows/release-build-publish.yml

Login by aws credendials action

---

.github/workflows/continuous-build.yml
testing/README.md
testing/terraform/testcases/linux_zip_cn.tfvars
testing/terraform/testcases/linux_zip_us_gov.tfvars

Verified this change with the workflow run in my fork:
https://github.com/srprash/aws-xray-daemon/actions/runs/2973373610
Also added a small Readme for explaining the testing suite.

Test linux zip in China & US Gov regions

---

CHANGELOG.md

*Issue #, if available:* N/A
*Description of changes:* Prepares v3.3.5 release

Release commit v3.3.5

---

CHANGELOG.md

Release commit v3.3.6

---

README.md

add performance report to readme

---

.github/workflows/continuous-build.yml
.github/workflows/release-build-publish.yml
Dockerfile
Dockerfile.amazonlinux
go.mod

Bump Go version to 1.20.3

---

CHANGELOG.md

*Issue #, if available:* N/A
*Description of changes:* Prepares 3.3.7 release

Release commit v3.3.7

---

CHANGELOG.md

Preparing XRay Daemon v3.3.8 release.

Release commit v3.3.8

---

.github/workflows/continuous-build.yml
.github/workflows/release-build-publish.yml
Dockerfile
Dockerfile.amazonlinux

Bump Go version to 1.21.3

---

CHANGELOG.md

Preparing XRay Daemon v3.3.9 release.

Release commit v3.3.9

---

.github/workflows/continuous-build.yml
.github/workflows/release-build-publish.yml
Dockerfile
Dockerfile.amazonlinux

Address CVEs
```
https://nvd.nist.gov/vuln/detail/CVE-2023-45285
https://nvd.nist.gov/vuln/detail/CVE-2023-39326
https://nvd.nist.gov/vuln/detail/CVE-2023-45283
https://nvd.nist.gov/vuln/detail/CVE-2023-45284
https://nvd.nist.gov/vuln/detail/CVE-2023-39326
https://nvd.nist.gov/vuln/detail/CVE-2023-45285
```

Bump Go version to 1.21.5

---

CHANGELOG.md

Releasing version 3.3.10
Updating the changelog.

Release commit v3.3.10

---

CHANGELOG.md

Release commit v3.3.11

---

CHANGELOG.md

Release commit v3.3.12

---

.github/workflows/continuous-build.yml
.github/workflows/release-build-publish.yml
Dockerfile
Dockerfile.amazonlinux

Address CVEs
https://nvd.nist.gov/vuln/detail/CVE-2024-24790

Bump Go version to 1.22.4

---

CHANGELOG.md

Release commit for X-Ray Daemon v3.3.13

Release commit v3.3.13

---

CHANGELOG.md

Release commit v3.3.14

---

.github/workflows/continuous-build.yml
.github/workflows/continuous-monitoring.yml
.github/workflows/release-build-publish.yml

*Description of changes:* Switch to using IAM Role that is more secure with short-lived credentials.

Switch from iam user to role

---

.github/workflows/continuous-build.yml
.github/workflows/release-build-publish.yml
Dockerfile
Dockerfile.amazonlinux

Addressing CVEs:
* 2025-22871
Per this issue: https://github.com/aws/aws-xray-daemon/issues/236
Tested by running `make build test`

Upgrade golang to 1.24.2

---

CHANGELOG.md

Release commit for X-Ray Daemon v3.3.15

Release commit v3.3.15

---

CHANGELOG.md

Update CHANGELOG to prepare for v3.4.0 release.

Release commit v3.4.0

---

CHANGELOG.md

Release commit v3.6.1
